# Generated by Django 3.2 on 2021-07-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('room_name', models.CharField(max_length=255)),
                ('message_text', models.TextField()),
                ('date_time_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('date_time_added',),
            },
        ),
    ]
